//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.11 at 06:09:54 PM EET 
//


package com.netcracker.solutions.etisalat.rvcpe.portal.hook.login.generatedmodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.netcracker.solutions.etisalat.rvcpe.portal.hook.login.generatedmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ValidateToken_QNAME = new QName("http://tokenvalidation.sso.onlineservices.etisalat.ae/", "validateToken");
    private final static QName _ValidateTokenResponse_QNAME = new QName("http://tokenvalidation.sso.onlineservices.etisalat.ae/", "validateTokenResponse");
    private final static QName _ValidateTokenRequestAdditionalInfoList_QNAME = new QName("", "AdditionalInfoList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.netcracker.solutions.etisalat.rvcpe.portal.hook.login.generatedmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValidateSSOTokenResponse }
     * 
     */
    public ValidateSSOTokenResponse createValidateSSOTokenResponse() {
        return new ValidateSSOTokenResponse();
    }

    /**
     * Create an instance of {@link ValidateTokenRequest }
     * 
     */
    public ValidateTokenRequest createValidateTokenRequest() {
        return new ValidateTokenRequest();
    }

    /**
     * Create an instance of {@link ValidateToken }
     * 
     */
    public ValidateToken createValidateToken() {
        return new ValidateToken();
    }

    /**
     * Create an instance of {@link ValidateTokenResponse }
     * 
     */
    public ValidateTokenResponse createValidateTokenResponse() {
        return new ValidateTokenResponse();
    }

    /**
     * Create an instance of {@link AttributeDto }
     * 
     */
    public AttributeDto createAttributeDto() {
        return new AttributeDto();
    }

    /**
     * Create an instance of {@link ValidateSSOTokenResponse.AdditionalInfoList }
     * 
     */
    public ValidateSSOTokenResponse.AdditionalInfoList createValidateSSOTokenResponseAdditionalInfoList() {
        return new ValidateSSOTokenResponse.AdditionalInfoList();
    }

    /**
     * Create an instance of {@link ValidateTokenRequest.AdditionalInfoList }
     * 
     */
    public ValidateTokenRequest.AdditionalInfoList createValidateTokenRequestAdditionalInfoList() {
        return new ValidateTokenRequest.AdditionalInfoList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateToken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tokenvalidation.sso.onlineservices.etisalat.ae/", name = "validateToken")
    public JAXBElement<ValidateToken> createValidateToken(ValidateToken value) {
        return new JAXBElement<ValidateToken>(_ValidateToken_QNAME, ValidateToken.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateTokenResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tokenvalidation.sso.onlineservices.etisalat.ae/", name = "validateTokenResponse")
    public JAXBElement<ValidateTokenResponse> createValidateTokenResponse(ValidateTokenResponse value) {
        return new JAXBElement<ValidateTokenResponse>(_ValidateTokenResponse_QNAME, ValidateTokenResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateTokenRequest.AdditionalInfoList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AdditionalInfoList", scope = ValidateTokenRequest.class)
    public JAXBElement<ValidateTokenRequest.AdditionalInfoList> createValidateTokenRequestAdditionalInfoList(ValidateTokenRequest.AdditionalInfoList value) {
        return new JAXBElement<ValidateTokenRequest.AdditionalInfoList>(_ValidateTokenRequestAdditionalInfoList_QNAME, ValidateTokenRequest.AdditionalInfoList.class, ValidateTokenRequest.class, value);
    }

}
