//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.11 at 06:09:54 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tokenvalidation.sso.onlineservices.etisalat.ae/")
package com.netcracker.solutions.etisalat.rvcpe.portal.hook.login.generatedmodel;
