//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.11 at 06:09:54 PM EET 
//


package com.netcracker.solutions.etisalat.rvcpe.portal.hook.login.generatedmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for validateTokenRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="validateTokenRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AdditionalInfoList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="additionalInfo" type="{http://tokenvalidation.sso.onlineservices.etisalat.ae/}attributeDto" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="requestFlag" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="serviceAccessPassword" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="serviceAccessUsername" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sourcChannel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "validateTokenRequest", propOrder = {
    "additionalInfoList",
    "requestFlag",
    "serviceAccessPassword",
    "serviceAccessUsername",
    "sourcChannel",
    "token"
})
public class ValidateTokenRequest {

    @XmlElementRef(name = "AdditionalInfoList", type = JAXBElement.class, required = false)
    protected JAXBElement<ValidateTokenRequest.AdditionalInfoList> additionalInfoList;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer requestFlag;
    @XmlElement(required = true)
    protected String serviceAccessPassword;
    @XmlElement(required = true)
    protected String serviceAccessUsername;
    @XmlElement(required = true)
    protected String sourcChannel;
    @XmlElement(required = true)
    protected String token;

    /**
     * Gets the value of the additionalInfoList property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ValidateTokenRequest.AdditionalInfoList }{@code >}
     *     
     */
    public JAXBElement<ValidateTokenRequest.AdditionalInfoList> getAdditionalInfoList() {
        return additionalInfoList;
    }

    /**
     * Sets the value of the additionalInfoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ValidateTokenRequest.AdditionalInfoList }{@code >}
     *     
     */
    public void setAdditionalInfoList(JAXBElement<ValidateTokenRequest.AdditionalInfoList> value) {
        this.additionalInfoList = value;
    }

    /**
     * Gets the value of the requestFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRequestFlag() {
        return requestFlag;
    }

    /**
     * Sets the value of the requestFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRequestFlag(Integer value) {
        this.requestFlag = value;
    }

    /**
     * Gets the value of the serviceAccessPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceAccessPassword() {
        return serviceAccessPassword;
    }

    /**
     * Sets the value of the serviceAccessPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceAccessPassword(String value) {
        this.serviceAccessPassword = value;
    }

    /**
     * Gets the value of the serviceAccessUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceAccessUsername() {
        return serviceAccessUsername;
    }

    /**
     * Sets the value of the serviceAccessUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceAccessUsername(String value) {
        this.serviceAccessUsername = value;
    }

    /**
     * Gets the value of the sourcChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcChannel() {
        return sourcChannel;
    }

    /**
     * Sets the value of the sourcChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcChannel(String value) {
        this.sourcChannel = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="additionalInfo" type="{http://tokenvalidation.sso.onlineservices.etisalat.ae/}attributeDto" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "additionalInfo"
    })
    public static class AdditionalInfoList {

        @XmlElement(nillable = true)
        protected List<AttributeDto> additionalInfo;

        /**
         * Gets the value of the additionalInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the additionalInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAdditionalInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AttributeDto }
         * 
         * 
         */
        public List<AttributeDto> getAdditionalInfo() {
            if (additionalInfo == null) {
                additionalInfo = new ArrayList<AttributeDto>();
            }
            return this.additionalInfo;
        }

    }

}
